### ISSUE TITLE
"ai" should *not* be the preferred extension name for `application/pdf`

### ISSUE THREAD

**Issue by aks** [mime-types/mime-types-data#25] opened 2019-10-02 21:57 UTC
It's ok if files ending with `.ai` acquire a MIME type of `application/pdf`, although the preferred MIME type for `.ai` files should really be `application/vnd.adobe.illustrator`.

It is *not* fine that the preferred filename extension for `application/pdf` is suddenly and abruptly changed from `.pdf` to `.ai`.

Billions of PDF documents around the world have *nothing* to do with Illustrator.

Downloading a file of `application/pdf` should default to a filename with a suffix of `.pdf`.  It must not default to `.ai`.

The only content type that should default to a suffix of `.ai`, should be `application/vnd.adobe.illustrator`.

**Comment by halostatue** [comment] 2019-10-02 22:22
This is a duplicate of #24, which will be merged and released when I’m back from vacation.

**Closed** 2019-10-02 22:24 UTC
